name: New Feature
description: A new feature
projects: ["agrc/6"]
body:
  - type: textarea
    attributes:
      label: Benefit
      description: Define the proposed measurable benefit to the end user or business
    validations:
      required: false
  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: Define the acceptance criteria to determine whether the implementation is correct and delivers the business benefit
      value: "- [ ] "
    validations:
      required: false
  - type: textarea
    attributes:
      label: Notes
      description: Any extra context or information about the feature
    validations:
      required: false
  - type: textarea
    attributes:
      label: Risks
      description: What risks can we resolve, own, accept, or mitigate
    validations:
      required: false
  - type: input
    attributes:
      value: "refs #"
      label: Issue Reference
    validations:
      required: false
