name: Issue Comment (Validate Addresses)

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  validate:
    name: ✅ Validate addresses
    runs-on: ubuntu-latest
    steps:
      - name: Add emoji to comment
        uses: actions/github-script@v7
        with:
          script: |
            const comment = context.payload.comment;
            const body = comment.body;

            if (!body.startsWith('/validate addresses')) {
              return;
            }

             github.rest.reactions.createForIssueComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: context.payload.comment.id,
                content: 'eyes'
              });
      - name: 🧪 Test addresses
        uses: agrc/validate-address-action@v1
        with:
          API_KEY: ${{ secrets.API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
